channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.2.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - ca-certificates=2022.12.7
  - certifi=2022.12.7
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.2.0
  - ipykernel=6.14.0
  - ipython=8.4.0
  - jedi=0.18.2
  - jupyter_client=7.0.6
  - jupyter_core=5.2.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - openssl=1.1.1s
  - packaging=23.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=22.3.1
  - platformdirs=3.0.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.14.0
  - python=3.9.16
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=19.0.2
  - readline=8.2
  - setuptools=65.6.3
  - six=1.16.0
  - sqlite=3.40.1
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.9.0
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - wcwidth=0.2.6
  - wheel=0.37.1
  - xz=5.2.10
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - attrs==22.2.0
    - cachetools==5.3.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - cmake==3.26.3
    - docker-pycreds==0.4.0
    - filelock==3.9.0
    - frozenlist==1.3.3
    - fsspec==2023.1.0
    - fst-pso==1.8.1
    - future==0.18.3
    - fuzzytm==2.0.5
    - gensim==4.3.0
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-auth==2.16.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.51.1
    - huggingface-hub==0.12.0
    - idna==3.4
    - importlib-metadata==6.0.0
    - isodate==0.6.1
    - jieba==0.42.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - lightning-utilities==0.6.0.post0
    - lit==16.0.1
    - markdown==3.4.1
    - markupsafe==2.1.2
    - miniful==0.0.6
    - mpmath==1.3.0
    - multidict==6.0.4
    - networkx==3.1
    - nltk==3.8.1
    - numpy==1.24.1
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nvtx-cu11==11.7.91
    - oauthlib==3.2.2
    - pandas==1.5.3
    - pathtools==0.1.2
    - pillow==9.5.0
    - protobuf==3.20.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyfume==0.2.25
    - pyparsing==3.0.9
    - pytorch-lightning==1.1.3
    - pytz==2022.7.1
    - pyyaml==6.0
    - rapidfuzz==2.13.7
    - rdflib==6.2.0
    - regex==2022.10.31
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - sacremoses==0.0.53
    - scikit-learn==1.2.1
    - scipy==1.10.0
    - sentencepiece==0.1.97
    - sentry-sdk==1.20.0
    - setproctitle==1.3.2
    - simpful==2.9.0
    - sklearn==0.0.post1
    - smart-open==6.3.0
    - smmap==5.0.0
    - sparqlwrapper==2.0.0
    - sympy==1.11.1
    - tensorboard==2.11.2
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.2.0
    - threadpoolctl==3.1.0
    - tokenizers==0.9.4
    - torch==2.0.0
    - torchmetrics==0.11.1
    - tqdm==4.64.1
    - transformers==4.1.1
    - triton==2.0.0
    - urllib3==1.26.14
    - wandb==0.15.0
    - werkzeug==2.2.2
    - yarl==1.8.2
    - zipp==3.12.0

