# -------- 灵活参数 --------

gpus : [0]  # 0 如果要CPU测试话
batch_size: 2
max_epochs: 400
# -------- 变量参数 --------



# -------- 默认参数 --------

path_read_train_csv: "../stores/train_df.csv"
path_read_test_csv: "../stores/test_df.csv"

model_name: "imxly/t5-pegasus-small"
model_base: "/home/fxb/projects/T5/downloads"


cache_dir_base: "/home/fxb/projects/T5/downloads"
checkpoint_path: "../outputs"

logging_dir: "../views/"
logging_name: "T5_human"


